dashboard/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("dashboard/", views.dashboard, name="dashboard"),
    path("template/", views.template, name="template"),
    path("reports/", views.reports, name="reports"),
    path("alerts/", views.alerts, name="alerts"),
    path("drones/", views.drones, name="drones"),
]

logins_and_alerts/urls.py
from django.urls import path

from . import views

app_name = 'loginsapp' 
urlpatterns = [
    path("signin/", views.loginuser, name="loginuser"),
    path("signout/", views.logoutuser, name="logoutuser"),
]

medidronebackend/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('newstuff.urls', namespace='homeapp')),
    path('login/', include('django.contrib.auth.urls')),
    path('login/', include('logins_and_alerts.urls', namespace='loginsapp')),
    path('api-auth/', include('rest_framework.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

newstuff/urls.py
from django.urls import path,include

from . import views

app_name = 'homeapp' 
urlpatterns = [
    path("dashboard/", views.dashboard, name="dashboard"),
    path("template/", views.template, name="template"),
    path("alerts/", views.alerts, name="alerts"),
    path("reports/", views.reports, name="reports"),
    path("team/", views.team, name="team"),
    path("settings/", views.settings, name="settings"),
    path("drones/", views.drones, name="drones"),
] 

logins_and_alerts/models.py
from django.db import models
from django.utils import timezone
import os

def custom_upload_to(instance, filename):
    extension = filename.split('.')[-1]
    filename = '{0}.{1}'.format(instance.username, extension)
    full_path = os.path.join('newstuff/static/images/avatar/', filename)
    if os.path.exists(full_path):
        os.remove(full_path)  
    return 'newstuff/static/images/avatar/{0}'.format(filename)

class User(models.Model):
    username = models.CharField(max_length=15,unique=True)
    displayname = models.CharField(max_length=30)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email = models.EmailField('User Email')
    title = models.CharField(max_length=20)
    description = models.TextField(blank=True)

    avatar = models.ImageField(null=True,blank=True,upload_to=custom_upload_to)
    userbg = models.CharField(blank=True,max_length=30)

    def __str__(self):
        return self.username

class Drone(models.Model):
    dronename = models.CharField('Drone',max_length=7)
    location = models.CharField(max_length=30)
    battiere = models.CharField('Battiere Percent',max_length=3)
    url = models.URLField(blank=True)
    active = models.BooleanField('Status')

    def __str__(self):
        return self.dronename

class Alert(models.Model):
    alertname = models.CharField('Alert',max_length=30)
    dronetarget = models.ForeignKey(Drone,on_delete=models.PROTECT)
    alertdescription = models.TextField('Description')

    def __str__(self):
        return self.alertname

newstuff/models.py
from django.db import models

# Create your models here.

logins_and_alerts/forms.py
from django import forms
from django.forms import ModelForm
from .models import User

class UserForm(ModelForm):
    class Meta:
        model = User
        fields = "__all__"
        

dashboard/views.py
from django.shortcuts import render
from rest_framework.response import Response
from rest_framework.decorators import api_view

def dashboard(request):
    return render(request, 'home.html')

def template(request):
    return render(request, 'empty.html')

def alerts(request):
    return render(request, "alerts.html")

def drones(request):
    return render(request, "drones.html")

def reports(request):
    return render(request, "reports.html")

def drone1(request):
    return render(request, "drone1.html")

@api_view(['GET'])
def getData(request):
    return Response()

logins_and_alerts/views.py
from django.shortcuts import render, redirect 
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from .forms import UserForm

def loginuser(request):
    if request.method == 'POST':
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('homeapp:dashboard')
        else:
            messages.success(request, ("The username or the password are incorrect"))
            # return redirect('signin')
            return render(request, 'login.html' ,{})
    else:
        return render(request, 'login.html' ,{})
    
def logoutuser(request):
    logout(request)
    messages.success(request, ("You have logout"))
    return redirect('homeapp:dashboard')

newstuff/views.py
from django.shortcuts import render
from rest_framework.response import Response
from rest_framework.decorators import api_view
from logins_and_alerts.models import Drone, User

def dashboard(request):   
    user_list = User.objects.all()  
    drone_list = Drone.objects.all()
    drone_active = 0
    drone_not_active = 0
    for drone in drone_list:
        if drone.active:
            drone_active = drone_active + 1
        else:
            drone_not_active = drone_not_active + 1
    # User_instance = User.objects.create(user=current_user)
    return render(request, 'home.html', {'drone_active': drone_active, 'drone_not_active': drone_not_active, 'drone_list': drone_list, 'user_list': user_list})

def template(request):
    user_list = User.objects.all()  
    return render(request, "empty.html", {'user_list': user_list})

def drones(request):
    user_list = User.objects.all()  
    drone_list = Drone.objects.all()
    
    return render(request, "drones.html", {'drone_list': drone_list, 'user_list': user_list})

def alerts(request):
    user_list = User.objects.all()  
    return render(request, "alerts.html", {'user_list': user_list})

def reports(request):
    user_list = User.objects.all()  
    return render(request, "reports.html", {'user_list': user_list})

def team(request):
    user_list = User.objects.all()  
    return render(request, "team.html", {'user_list': user_list})

def settings(request):
    user_list = User.objects.all()  
    return render(request, "settings.html", {'user_list': user_list})                 

dashboard/templates/alerts.html
{% extends "base.html" %}

{% load static %}

{% block main %}
<p>a </p>
{% endblock %}

{% block others %}
{% endblock %}

dashboard/templates/empty.html
{% extends "base.html" %}

{% load static %}

{% block main %}
<p>a </p>
{% endblock %}

{% block others %}
{% endblock %}

dashboard/templates/reports.html
{% extends "base.html" %}

{% load static %}

{% block main %}
<p>a </p>
{% endblock %}

{% block others %}
{% endblock %}

newstuff/templates/alerts.html
{% extends "base.html" %}

{% load static %}

{% block active %}
    <li>
        <a href="{%url 'homeapp:dashboard' %}">
            <i class='bx bxs-dashboard bx-rotate-90' style='color:rgb(0, 0, 0), 255, 0;'></i>
            <span class="text">Dashboard</span>
        </a>
    </li>
    <li>
        <a href="{%url 'homeapp:drones' %}">
            <i class='bx bx-command bx-rotate-90' style='color:rgb(0, 0, 0)'></i>
            <span class="text">Drones</span>
        </a>
    </li>
    <li>
        <a href="{%url 'homeapp:reports' %}">
                <i class='bx bxs-report'></i>
            <span class="text">Reports</span>
        </a>
    </li>
    <li class="active">
        <a href="{%url 'homeapp:alerts' %}">
            <i class='bx bx-bell' style='color:rgb(0, 0, 0)'></i>
            <span class="text">Alerts</span>
        </a>
    </li>
    <li>
        <a href="{%url 'homeapp:team' %}">
            <i class='bx bxs-group' ></i>
            <span class="text">Team</span>
        </a>
    </li>
{% endblock %}

{% block main %}
{% endblock %}

{% block sidebar %}
    <li>
        <a href="{%url 'homeapp:settings' %}">
            <i class='bx bxs-cog' ></i>
            <span class="text">Settings</span>
        </a>
    </li>
{% endblock %}

newstuff/templates/base.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>
	{% block style %}
	{% endblock %}

	<style> 
		.button {
		border: none;
		color: rgba(255, 255, 255, 0);
		padding: 12px 30px;
		text-align: center;
		text-decoration: none;
		display: inline-block;
		font-size: 16px;
		margin: 4px 2px;
		transition-duration: 0.4s;
		cursor: pointer;
		}

		.button1 {
		background-color: white; 
		color: black; 
		border: 2px solid #04AA6D;
		}

		.button1:hover {
		background-color: #04AA6D;
		color: white;
		}

		.button2 {
		background-color: rgba(255, 255, 255, 0); 
		color: black; 
		border: 2px solid #008CBA;
		}

		.button2:hover {
		background-color: #008CBA;
		color: white;
		}
	</style>

	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<!-- Boxicons -->
	<link href='https://unpkg.com/boxicons@2.0.9/css/boxicons.min.css' rel='stylesheet'>
	<!-- My CSS -->
	<link rel="stylesheet" href="{% static 'css/style.css'%}">

	<title>Medicale Drone</title>
</head>
<body>


	<!-- SIDEBAR -->
	<section id="sidebar">
		<a href="{%url 'homeapp:dashboard' %}" class="brand">
			<img class="text"; src = "{% static 'images/oopssmaller.png'%}"></i>
			<span class="text">MediDrone</span>
		</a>
		<ul class="side-menu top">
			{% block active %}

			{% endblock %}
		</ul>
		<ul class="side-menu bottom">
		{% block sidebar%}
		{% endblock %}
			{% if user.is_authenticated %}
			<li>
				<a href="{%url 'loginsapp:logoutuser' %}" class="logout">
					<i class='bx bxs-log-out-circle' ></i>
					<span class="text">Logout</span>
				</a>
			</li>
			{% endif %}
		</ul>
	</section>
	<!-- SIDEBAR -->



	<!-- CONTENT -->
	<section id="content">
		<!-- NAVBAR -->
		<nav>
			<i class='bx bx-menu' ></i>
			<a href="#" class="nav-link">Categories</a>
			<form action="#">
				<div class="form-input">
					<input type="search" placeholder="Search...">
					<button type="submit" class="search-btn"><i class='bx bx-search' ></i></button>
				</div>
			</form>
			{% if messages %}
                {% for message in messages %}
                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                    {{message}}
                  </div>
                {% endfor %}
            {% endif %}
			<input type="checkbox" id="switch-mode" hidden>
			<a href="#" class="notification">
				<i class='bx bxs-bell' ></i>
				<span class="num">8</span>
			</a>
				{% if user.is_authenticated %}
					{% for curuser in user_list %}
						{% if user.username == curuser.username %}
						<a class="profile"> 
							<img src="{% static 'images/avatar/' %}{{ user.username }}.png" alt="Avatar" href="#">	
						</a>					
						{% else %}
						<a class="profile"> 
							<img src="{% static 'images/mapdrone.jpg'%}" alt="Avatar" href="#">	
						</a>
						{% endif %}
					{% endfor %}
				{% else %}
				<a class="profile" href= "{%url 'loginsapp:loginuser' %}"> 
					<button type="link" class="button button2">Log In</button>
				</a>
				{% endif %}
		</nav>
		<!-- NAVBAR -->

		{% block popup %}
		{% endblock %}
		<!-- MAIN -->
		<main>
			{% block main %}
			{% endblock %}
		</main>
		<!-- MAIN -->
	</section>
	<!-- CONTENT -->
	

	<script src="{% static 'js/script.js'%}"></script>

	{% block js %}
	{% endblock %}
</body>
</html>

newstuff/templates/drones.html
{% extends "base.html" %}

{% load static %}

{% block style %}
        <link rel="stylesheet" href="{% static 'css/jquery.css' %}" />
		<link rel="stylesheet" href="{% static 'css/swiper.css' %}" />

		<!-- Theme CSS -->
		<link rel="stylesheet" href="{% static 'css/bpl.css' %}" />

        <style>
            .image-maps-container {
                display: flex;
            }
        
            .connected {
                color: green;
            }
        
            .disconnected {
                color: red;
            }
        
            .maps-container {
                flex-grow: 1;
                padding-left: 10px;
                /* Adjust spacing between image and maps */
            }
        </style>
{% endblock %}

{% block active %}
    <li>
        <a href="{%url 'homeapp:dashboard' %}">
            <i class='bx bxs-dashboard bx-rotate-90' style='color:rgb(0, 0, 0), 255, 0;'></i>
            <span class="text">Dashboard</span>
        </a>
    </li>
    <li class="active">
        <a href="{%url 'homeapp:drones' %}">
            <i class='bx bx-command bx-rotate-90' style='color:rgb(0, 0, 0)'></i>
            <span class="text">Drones</span>
        </a>
    </li>
    <li>
        <a href="{%url 'homeapp:reports' %}">
                <i class='bx bxs-report'></i>
            <span class="text">Reports</span>
        </a>
    </li>
    <li>
        <a href="{%url 'homeapp:alerts' %}">
            <i class='bx bx-bell ' style='color:rgb(0, 0, 0)'></i>
            <span class="text">Alerts</span>
        </a>
    </li>
    <li>
        <a href="{%url 'homeapp:team' %}">
            <i class='bx bxs-group' ></i>
            <span class="text">Team</span>
        </a>
    </li>
{% endblock %}

{% block popup %}
{% for drone in drone_list %}
    {% if drone.active %}
        <body class="page__joblist">
            <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog modal-lg">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">{{drone.dronename}} Stream</h5>
                            <button type="button" class="btn-close modal-close" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            <!-- Container for image and maps -->
                            <div class="image-maps-container">
                                <!-- Image with border -->
                                <div class="image-container">
                                    <img src={{drone.url}} width="352" height="288" alt="Image">
                                </div>
                                <!-- Iframe -->
                                <div class="maps-container">
                                    <div class="image-container">
                                        <img src="{% static 'images/map.png' %}" width="352" height="288" alt="Image">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <!-- You can add additional buttons or content here if needed -->
                        </div>
                    </div>
                </div>
            </div>
    {% endif %}
{% endfor %}
{% endblock %}
 
{% block main %}
{% for drone in drone_list %}
    {% if drone.active %}
        <div class="container-xxl">
            <div class="d-flex flex-column flex-xl-row align-items-xl-center gap-20">
                
                </div>
            </div>

            <div class="d-grid mt-60 gap-34">
                <div class="job-card-harizontal">
                    <button class="btn btn-rounded btn-white position-absolute d-xl-none top-100 start-50 p-10 translate-middle" type="button" data-bs-toggle="collapse" data-bs-target="#jobInfoCardCollapse" aria-expanded="false" aria-controls="jobInfoCardCollapse">
                        <img src="{% static 'images/chevron-down.svg' %}" class="svg-inject text-primary is-16" alt="" />
                    </button>
                    <div class="job-info">
                        <div class="job-image">
                            <img src="{% static 'images/drone.svg' %}" alt="" />
                        </div>
                        <div class="job-info-inner">
                            <h5 class="job-title">
                                <a href="">{{drone.dronename}}</a>
                            </h5>
                            <div>
                                <t class="connected">Connected</t>
                            </div>
                        </div>
                    </div>
                    <div class="job-info-card-collapse collapse" id="jobInfoCardCollapse">
                        <div class="job-info-card">
                            <div class="info-card">
                                <div class="info-card-icon bg-ufo-green-100 rounded-pill">
                                    <img src="{% static 'images/sssvg.svg' %}" class="svg-inject svg-icon" alt="" />
                                </div>
                                <div class="info-card-content">
                                    <h6 class="info-card-title">{{drone.battiere}} %</h6>
                                    <div class="info-card-desc">Battery</div>
                                </div>
                            </div>
                            <div class="info-card">
                                <div class="info-card-icon bg-rajah rounded-pill">
                                    <img src="{% static 'images/mark.svg'%}" class="svg-inject svg-icon" alt="" />
                                </div>
                                <div class="info-card-content">
                                    <h6 class="info-card-title">{{drone.location}}</h6>
                                    <div class="info-card-desc">Location</div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="job-action">
                        <a class="btn btn-apply OPSS flex-fill flex-md-nofill fw-semiBold py-12 px-43 rounded-pill"
                                href="/jobdetail.html">Watch Now</a>

                    </div>
                </div>
                <!-- /.job-card-grid-harizontal-component -->

            </div>
    {% else %}
    <div class="d-grid mt-60 gap-34">
        <div class="job-card-harizontal">
            <button class="btn btn-rounded btn-white position-absolute d-xl-none top-100 start-50 p-10 translate-middle" type="button" data-bs-toggle="collapse" data-bs-target="#jobInfoCardCollapse" aria-expanded="false" aria-controls="jobInfoCardCollapse">
                <img src="{% static 'images/chevron-down.svg' %}" class="svg-inject text-primary is-16" alt="" />
            </button>
            <div class="job-info">
                <div class="job-image">
                    <img src="{% static 'images/drone.svg' %}" alt="" />
                </div>
                <div class="job-info-inner">
                    <h5 class="job-title">
                        <a href="">{{drone.dronename}}</a>
                    </h5>
                    <div class="job-author">
                        <t class="disconnected">Disconnected</t>
                    </div>
                </div>
            </div>
            <div class="job-info-card-collapse collapse" id="jobInfoCardCollapse">
                <div class="job-info-card">
                    <div class="info-card">
                        <div class="info-card-icon bg-ufo-green-100 rounded-pill">
                            <img src="{% static 'images/sssvg.svg' %}" class="svg-inject svg-icon" alt="" />
                        </div>
                        <div class="info-card-content">
                            <h6 class="info-card-title">{{drone.battiere}}</h6>
                            <div class="info-card-desc">Battery</div>
                        </div>
                    </div>
                    <div class="info-card">
                        <div class="info-card-icon bg-rajah rounded-pill">
                            <img src="{% static 'images/mark.svg'%}" class="svg-inject svg-icon" alt="" />
                        </div>
                        <div class="info-card-content">
                            <h6 class="info-card-title">{{drone.location}}</h6>
                            <div class="info-card-desc">Location</div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="job-action">
                <a class="btn btn-apply flex-fill flex-md-nofill fw-semiBold py-12 px-43 rounded-pill"
						href="">Refresh</a>

            </div>
        </div>
        <!-- /.job-card-grid-harizontal-component -->

    </div>
    {% endif %}
{% endfor %}
{% endblock %}

{% block sidebar %}
    <li>
        <a href="{%url 'homeapp:settings' %}">
            <i class='bx bxs-cog' ></i>
            <span class="text">Settings</span>
        </a>
    </li>
{% endblock %}

{% block js %}
        <script src="{% static 'js/oops.js' %}"></script>
        <script src="{% static 'js/bootstrap.js' %}"></script>


		<!-- Vendors -->
		<script src="{% static 'js/jquery1.js' %}"></script>
		<script src="{% static 'js/jquery2.js' %}"></script>
		<script src="{% static 'js/swiper.js' %}"></script>
		<script src="{% static 'js/svg.js' %}"></script>
		<script src="{% static 'js/fslightbox.js' %}"></script>

		<!-- Template Function -->
		<script src="{% static 'js/theme.js' %}"></script>
{% endblock %}

newstuff/templates/home.html
{% extends "base.html" %}

{% load static %}

{% block active %}
    <li class="active">
        <a href="{%url 'homeapp:dashboard' %}">
            <i class='bx bxs-dashboard bx-rotate-90' style='color:rgb(0, 0, 0), 255, 0;'></i>
            <span class="text">Dashboard</span>
        </a>
    </li>
    <li>
        <a href="{%url 'homeapp:drones' %}">
            <i class='bx bx-command bx-rotate-90' style='color:rgb(0, 0, 0)'></i>
            <span class="text">Drones</span>
        </a>
    </li>
    <li>
        <a href="{%url 'homeapp:reports' %}">
                <i class='bx bxs-report'></i>
            <span class="text">Reports</span>
        </a>
    </li>
    <li>
        <a href="{%url 'homeapp:alerts' %}">
            <i class='bx bx-bell ' style='color:rgb(0, 0, 0)'></i>
            <span class="text">Alerts</span>
        </a>
    </li>
    <li>
        <a href="{%url 'homeapp:team' %}">
            <i class='bx bxs-group' ></i>
            <span class="text">Team</span>
        </a>
    </li>
{% endblock %}

{% block main %}
    <div class="head-title">
        <div class="left">
            <h1>Dashboard</h1>
            <ul class="breadcrumb">
                <li>
                    <a href="{%url 'homeapp:dashboard'%}">Dashboard</a>
                </li>
                <li><i class='bx bx-chevron-right' ></i></li>
                <li>
                    <a class="active" href="#">Home</a>
                </li>
            </ul>
        </div>
        <a href="{% static 'images/MediDrone.pdf' %}" class="btn-download">
            <i class='bx bxs-cloud-download' ></i>
            <span class="text">Download Manual</span>
        </a>
    </div>

    <ul class="box-info">
        <li>
            <i class='bx bxs-calendar-check' ></i>
            <span class="text">
                <h3> {{ drone_active }} </h3>
                <p>Active Drone</p>
            </span>
        </li>
        <li>
            <i class='bx bxs-group' ></i>
            <span class="text">
                <h3> {{ drone_not_active }} </h3>
                <p>Inactive Drones</p>
            </span>
        </li>
        <li>
            <i class='bx bxs-dollar-circle' ></i>
            <span class="text">
                <h3>0</h3>
                <p>Alerts</p>
            </span>
        </li>
    </ul>


    <div class="table-data">
        <div class="order">
            <div class="head">
                <h3>Recent Alerts</h3>
                <i class='bx bx-search' ></i>
                <i class='bx bx-filter' ></i>
            </div>
            <table>
                <thead>
                    <tr>
                        <th>Drone</th>
                        <th>Alert Date</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody>
                    {% for drone in drone_list %}
                        {% if drone.active %}
                            <tr>
                                <td>
                                    <img src="{% static 'images/drone.svg' %}">
                                    <p>{{drone.dronename}}</p>
                                </td>
                                <td>01-10-2021</td>
                                <td><span class="status completed">Completed</span></td>
                            </tr>
                        {% else %}
                            <tr>
                                <td>
                                    <img src="{% static 'images/drone.svg' %}">
                                    <p>{{drone.dronename}}</p>
                                </td>
                                <td>01-10-2021</td>
                                <td><span class="status pending">Pending</span></td>
                            </tr>
                        {% endif %}
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="todo">
            <div class="head">
                <h3>Available EMTs</h3>
                <i class='bx bx-plus' ></i>
                <i class='bx bx-filter' ></i>
            </div>
            <ul class="todo-list">
                <li class="completed">
                    <p>EMT 12</p>
                    <i class='bx bx-dots-vertical-rounded' ></i>
                </li>
                <li class="completed">
                    <p>EMT 13</p>
                    <i class='bx bx-dots-vertical-rounded' ></i>
                </li>
                <li class="not-completed">
                    <p>EMT 14</p>
                    <i class='bx bx-dots-vertical-rounded' ></i>
                </li>
                <li class="completed">
                    <p>EMT 15</p>
                    <i class='bx bx-dots-vertical-rounded' ></i>
                </li>
                <li class="not-completed">
                    <p>EMT 16</p>
                    <i class='bx bx-dots-vertical-rounded' ></i>
                </li>
            </ul>
        </div>
    </div>
{% endblock %}

{% block sidebar %}
    <li>
        <a href="{%url 'homeapp:settings' %}">
            <i class='bx bxs-cog' ></i>
            <span class="text">Settings</span>
        </a>
    </li>
{% endblock %}

newstuff/templates/reports.html
{% extends "base.html" %}

{% load static %}

{% block active %}
    <li>
        <a href="{%url 'homeapp:dashboard' %}">
            <i class='bx bxs-dashboard bx-rotate-90' style='color:rgb(0, 0, 0), 255, 0;'></i>
            <span class="text">Dashboard</span>
        </a>
    </li>
    <li>
        <a href="{%url 'homeapp:drones' %}">
            <i class='bx bx-command bx-rotate-90' style='color:rgb(0, 0, 0)'></i>
            <span class="text">Drones</span>
        </a>
    </li>
    <li class="active">
        <a href="{%url 'homeapp:reports' %}">
                <i class='bx bxs-report'></i>
            <span class="text">Reports</span>
        </a>
    </li>
    <li>
        <a href="{%url 'homeapp:alerts' %}">
            <i class='bx bx-bell ' style='color:rgb(0, 0, 0)'></i>
            <span class="text">Alerts</span>
        </a>
    </li>
    <li>
        <a href="{%url 'homeapp:team' %}">
            <i class='bx bxs-group' ></i>
            <span class="text">Team</span>
        </a>
    </li>
{% endblock %}

{% block main %}
{% endblock %}

{% block sidebar %}
    <li>
        <a href="{%url 'homeapp:settings' %}">
            <i class='bx bxs-cog' ></i>
            <span class="text">Settings</span>
        </a>
    </li>
{% endblock %}

newstuff/templates/settings.html
{% extends "base.html" %}

{% load static %}

{% block active %}
    <li>
        <a href="{%url 'homeapp:dashboard' %}">
            <i class='bx bxs-dashboard bx-rotate-90' style='color:rgb(0, 0, 0), 255, 0;'></i>
            <span class="text">Dashboard</span>
        </a>
    </li>
    <li>
        <a href="{%url 'homeapp:drones' %}">
            <i class='bx bx-command bx-rotate-90' style='color:rgb(0, 0, 0)'></i>
            <span class="text">Drones</span>
        </a>
    </li>
    <li>
        <a href="{%url 'homeapp:reports' %}">
                <i class='bx bxs-report'></i>
            <span class="text">Reports</span>
        </a>
    </li>
    <li>
        <a href="{%url 'homeapp:alerts' %}">
            <i class='bx bx-bell ' style='color:rgb(0, 0, 0)'></i>
            <span class="text">Alerts</span>
        </a>
    </li>
    <li>
        <a href="{%url 'homeapp:team' %}">
            <i class='bx bxs-group' ></i>
            <span class="text">Team</span>
        </a>
    </li>
{% endblock %}

{% block main %}
{% endblock %}

{% block sidebar %}
    <li class = "active">
        <a href="{%url 'homeapp:settings' %}">
            <i class='bx bxs-cog' ></i>
            <span class="text">Settings</span>
        </a>
    </li>
{% endblock %}

newstuff/templates/team.html
{% extends "base.html" %}

{% load static %}

{% block active %}
    <li>
        <a href="{%url 'homeapp:dashboard' %}">
            <i class='bx bxs-dashboard bx-rotate-90' style='color:rgb(0, 0, 0), 255, 0;'></i>
            <span class="text">Dashboard</span>
        </a>
    </li>
    <li>
        <a href="{%url 'homeapp:drones' %}">
            <i class='bx bx-command bx-rotate-90' style='color:rgb(0, 0, 0)'></i>
            <span class="text">Drones</span>
        </a>
    </li>
    <li>
        <a href="{%url 'homeapp:reports' %}">
                <i class='bx bxs-report'></i>
            <span class="text">Reports</span>
        </a>
    </li>
    <li>
        <a href="{%url 'homeapp:alerts' %}">
            <i class='bx bx-bell ' style='color:rgb(0, 0, 0)'></i>
            <span class="text">Alerts</span>
        </a>
    </li>
    <li class="active">
        <a href="{%url 'homeapp:team' %}">
            <i class='bx bxs-group' ></i>
            <span class="text">Team</span>
        </a>
    </li>
{% endblock %}

{% block main %}
{% endblock %}

{% block sidebar %}
    <li>
        <a href="{%url 'homeapp:settings' %}">
            <i class='bx bxs-cog' ></i>
            <span class="text">Settings</span>
        </a>
    </li>
{% endblock %}